# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4acd2df0aeead5933ff62b692707c2bee779e737f495c4d9d307c458c34642e60bd63527fffc8cf03aff7db2743215497653ee0ac2ce0a56120f3deadc5e6098

test:
  secret_key_base: bb591830f35922fa7dbc6385cdd6f0020a84a67df4ea017b6d0fd132dc55226cc49f813c9746b94d17c8b4a735af010460c206c39f870b3d17bade8c18ba528f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
